### ISSUE TITLE
has_many_aggregate with a condition?

### ISSUE THREAD

**Issue by jrochkind** [clio/jit_preloader#13]
Imagine I have a list of Users. Each user has Posts. A Post can be `public` or not. 

I'm going to go through the list of Users, and for each one I want to display the count of public posts. 

```
<%= users.each do |user| %>
   <%= user.name %> has <%= user.posts.public.count %>
   ^^^ With a scope, or just where an ordinary "where" is fine too..
   <%= user.name %> has <%= user.posts.where(public: true).count %>
<% end %>
```

Can I use `has_many_aggregate` for this? The thing that is not covered by the example/typical usage is that extra "where" clause (possibly hidden in a scope), to be just _certain_ posts belonging to a user, not the count of everything on the other side of the association. 

Advice?

**Comment by doliveirakn** [comment]
Hey @jrochkind

In general, we can't used the gem to load association counts that require additional Scopes. 

However you can make an association that includes the scope and that can be used. 

(Trying to write this on my phone so I can't test to guarantee it is correct)

```ruby
class User
  has_many :public_posts, ->{ public }, class_name: "Post"
  has_many_aggregrate :public_posts, :count_all, :count, "*"
end
```

After which you should be able to use
`user.public_posts_count_all` which should allow you to preload these counts just in time to be used. 

Would this solve your issue?

**Comment by jrochkind** [comment]
Ah, that makes sense. Not sure if I like it, but it answers the question!
