### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by jonian** [clio/jit_preloader#23]
Hi, thank you for this gem!  
Are you planning to add rails 6 support?

**Comment by doliveirakn** [comment]
This is definitely on my todo list, however I haven't been able to really dig into it yet. 

If you are able to create an issue with what is broken on Rails 6 it will help shortcut some of the investigation i'd need to do.

**Comment by jonian** [comment]
Thank you for the quick response @doliveirakn! I will do some testing on rails 6 and will report back.

**Comment by jonian** [comment]
The only change that I think is required is the `run` method patch on [PreloaderAssociation](https://github.com/clio/jit_preloader/blob/master/lib/jit_preloader/active_record/associations/preloader/association.rb#L20) module. All specs ran successfully and manual tests on a real application were successful.

```ruby
# Rails 6 patched method
# original: https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/associations/preloader/association.rb#L15
def run
  all_records = []

  owners.each do |owner|
    owned_records = records_by_owner[owner] || []
    all_records.concat(Array(owned_records)) if owner.jit_preloader || JitPreloader.globally_enabled?
    associate_records_to_owner(owner, owned_records)
  end

  JitPreloader::Preloader.attach(all_records) if all_records.any?

  self
end
```

I adapted the changes from [here](https://github.com/EnzymeCorp/jit_preloader/blob/rails-6/lib/jit_preloader/active_record/associations/preloader/association.rb). The specs are failing if all changes from that fork are applied.

**Comment by muyiwaoyeniyi** [comment]
+1
