### ISSUE TITLE
Enable usage with Rails 6.1.4.1

### ISSUE THREAD

**Issue by Aelphaeis** [clio/jit_preloader#43]
Presently, the jit_preloader only supports up to rails 6.0.0; however, for manage, we wish to ensure that it works with rails 6.1.4.1 (the next version of rails we wish to upgrade to).

This issue is to update the jit_preloader to work with this version.

**Comment by doliveirakn** [comment]
@Aelphaeis can you release the new version of the gem?

**Comment by Aelphaeis** [comment]
> @Aelphaeis can you release the new version of the gem?

I've already created a draft; however, I wish to test this more thoroughly before making a full release.

**Comment by doliveirakn** [comment]
@Aelphaeis  Do you have an approximate timeline on that?
