### ISSUE TITLE
Add explicit method to clear `jit_preload_aggregates` memoization

### ISSUE THREAD

**Issue by mcramm** [clio/jit_preloader#6]
This is currently being done through the `reload` method on `active_record/base`

https://github.com/clio/jit_preloader/blob/master/lib/jit_preloader/active_record/base.rb#L10

This new method would simply be a more explicit version like `clear_jit_preload_aggregate_cache` or similar, that `reload` could leverage.

**Comment by doliveirakn** [comment]
@mcramm I opened a PR for this issue if you'd like to review it.
